### ISSUE TITLE
Add New GET method to fetch all contents

### ISSUE THREAD

**Issue by yhoungdev** [yhoungdev/Private-me-Backend#8]
Create API to fetch all contents from contents model

**Comment by ays14** [comment]
Hi @yhoungdev , I would like to take this up but I was not able to find a model for `Contents`. Can you help me here with the required fields and I can the create schema and APIs for the same.

**Comment by yhoungdev** [comment]
Sure I have created the POST method for that so I will assign and tell you the model name

**Comment by yhoungdev** [comment]
assigned to you

**Comment by yhoungdev** [comment]
@ays14 I will assign another issue to you by God's grace.

Also you can checkout the frontend here 

https://github.com/yhoungdev/Private-me-

**Comment by ays14** [comment]
Alright @yhoungdev , no worries. Happy Hacking :)
